<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Alife.Client</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\Alife\Alife.Application\Alife.Application.csproj" />
    </ItemGroup>
</Project>
