<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Alife.Framework</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Alife.Framework\Alife.Framework.csproj"/>
        <ProjectReference Include="..\Alife.PluginSystem\Alife.PluginSystem.csproj"/>
    </ItemGroup>

</Project>
