<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Alife\Alife.Framework\Alife.Framework.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.Core" Version="1.1.0" />
  </ItemGroup>
</Project>