<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Alife.Platform\Alife.Platform.csproj" />
      <ProjectReference Include="..\Alife.PluginSystem\Alife.PluginSystem.csproj" />
    </ItemGroup>

</Project>
